### ISSUE TITLE
Improve diagnostics format

### ISSUE THREAD

**Issue by andy-z** [andy-z/ged2doc#18]
Diagnostics produced by ged2doc for error conditions is a bit unwieldy and may be hard to grok for regular users, example:
```
ERROR: ged2doc.cli (cli.py:232) -- caught exception: Invalid syntax at line 400: `b'''
Traceback (most recent call last):
  File "/home/salnikov/ged2doc/ged2doc/cli.py", line 230, in main
    writer.save()
  File "/home/salnikov/ged2doc/ged2doc/writer.py", line 111, in save
    for indi in reader.records0('INDI'):
  File "/home/salnikov/venv-3.6/lib/python3.6/site-packages/ged4py/parser.py", line 278, in records0
    for offset, xtag in self.index0:
  File "/home/salnikov/venv-3.6/lib/python3.6/site-packages/ged4py/parser.py", line 171, in index0
    self._init_index()
  File "/home/salnikov/venv-3.6/lib/python3.6/site-packages/ged4py/parser.py", line 196, in _init_index
    for gline in self.gedcom_lines(self._bom_size):
  File "/home/salnikov/venv-3.6/lib/python3.6/site-packages/ged4py/parser.py", line 259, in gedcom_lines
    "{0}: `{1}'".format(lineno, line))
ged4py.parser.ParserError: Invalid syntax at line 400: `b'''
ERROR: ged2doc.cli (cli.py:233) -- Error while producing a document: Invalid syntax at line 400: `b'''
```
Would be nice to improve and make clearer w.r.t. what the actual error is. Would still be useful to keep traceback info maybe in shortened form.

Separate and more interesting issue is a localization of error messages, but I'm sure it's a more complicated task.

**Comment by FlominatorTM** [comment]
Finding the reason for this, was even more challenging ;)

> ERROR: ged2doc.cli (cli.py:232) -- caught exception: 'str' object has no attribute 'decode'
> Traceback (most recent call last):
>   File "c:\program files (x86)\python\lib\site-packages\ged2doc\cli.py", line 230, in main
>     writer.save()
>   File "c:\program files (x86)\python\lib\site-packages\ged2doc\writer.py", line 111, in save
>     for indi in reader.records0('INDI'):
>   File "c:\program files (x86)\python\lib\site-packages\ged4py\parser.py", line 281, in records0
>     yield self.read_record(offset)
>   File "c:\program files (x86)\python\lib\site-packages\ged4py\parser.py", line 340, in read_record
>     rec.value = rec.value.decode(self._encoding, self._errors)
> AttributeError: 'str' object has no attribute 'decode'
> ERROR: ged2doc.cli (cli.py:233) -- Error while producing a document: 'str' object has no attribute 'decode'
> 

I added debug output to the code in order to see the line that caused the problem. In the code I saw that ged2doc does logging. How can I access the log?

**Comment by andy-z** [comment]
> I added debug output to the code in order to see the line that caused the problem. In the code I saw that ged2doc does logging. How can I access the log?

Try to add `-v -v` on command line.

**Comment by andy-z** [comment]
Also, @FlominatorTM, if you have found a problem, please, open new issue, this ticket is for improving message format.

**Comment by andy-z** [comment]
Another possible improvement for logging is to make simpler for Windows folks to produce file with logging information to email it to me. I think I would get rid of `-v` option and replace it with `--log=filename.log` which would log all logging levels to a file. It may still be useful to output errors to console as well in that case too.

**Comment by andy-z** [comment]
Built release 0.1.14 with these improvements.

**Comment by FlominatorTM** [comment]
Now is a lot more helpful. Thank you.
