### ISSUE TITLE
Missing Ancestor tree in ODT output

### ISSUE THREAD

**Issue by Mejstro** [andy-z/ged2doc#21]
Hello,
After exporting GEDCOM to ODT, I can see missing Ancestor tree images. MS Word 2016 tells that the image is impossible to display. Other photos of people in the GEDCOM are displayed normally:
Export to HTML works as expected without any issues.
![missing_ancestor_tree](https://user-images.githubusercontent.com/7621445/40769293-238dcb1a-64a7-11e8-950f-1f02e560e663.JPG)

OS: Windows 7 Enterprise
Ged2Doc version: 0.1.14 (ged4py 0.1.9)
MS Office: 2016

**Comment by andy-z** [comment]
MS Office compatibility with OpenDocument formats is not perfect. For best results use OpenOffice/LibreOffice (I test `ged2doc` output with LibreOffice). I tried to see some time ago what MS Word did not like in particular on ODT file produced by `ged2doc` but could not find any clue. I'll try to check again but I cannot promise anything and I don't have much time to spend on that.

**Comment by andy-z** [comment]
@Mejstro, there was a small change in v0.1.15 (just released) related to ancestor trees (svg header tag should be more conforming now). It can potentially fix Microsoft problem though not very likely (it did not work in my Word 2013, but MS official support for SVG only appeared in Word 2016). You can try loading ODT made with v0.1.15 into MS Word to see if that helped. Again, Open/LibreOffice are the only supported applications for now.

**Comment by Mejstro** [comment]
Hi Andy,
The Microsoft Office issue has not been solved by this fix. Images are still shown in the LibreOffice only...
If I could help in the future (with testing for example), I would be very glad...
Best regards
Jan

**Comment by andy-z** [comment]
@Mejstro, sorry for long delay in trying to address this. I have just published v0.3.0 (https://github.com/andy-z/ged2doc/releases/tag/v0.3.0), it should improve MS Office compatibility. Could you try it and let me know how it works for you?

This section in docs could also be helpful: https://ged2doc.readthedocs.io/en/latest/usage.html#odt-details

**Comment by Mejstro** [comment]
Hello Andy,
Thank you very much for your notification.
I have already tested the new release and it works great!
Thank you very much...Good work!
Best regards
Mejstro


po 3. 8. 2020 v 9:17 odesílatel Andy <notifications@github.com> napsal:
